server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: adminservice
  cluster-name-expression: new String("default")
  combine-host-port: true
