server:
  port: 9763
ribbon:
  ReadTimeout: 3000
  SocketTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
zuul:
  sensitive-headers:
  routes:
    configservice:
      path: /config/**
    authservice:
      path: /auth/**