version: "3"
services:
  configservice:
    image: com.labrador/configservice:latest
    ports:
      - "8888:8888"
  eurekaservice:
    image: com.labrador/eurekaservice:latest
    depends_on: 
      - configservice
    ports:
      - "8761:8761"
    restart: on-failure
  # authservice:
  #   image: com.labrador/authservice:latest
  #   ports:
  #     - "6060:6060"
  #   depends_on:
  #     - configservice
  #     - eurekaservice
  #   restart: on-failure
