server:
  port: 6062
eureka:
  client:
    enabled: false

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/accountservice?useSSL=false
  messages:
    basename: messages, ValidationMessges, classpath*:ValidationMessages
  flyway:
    locations: classpath:db/migration/{vendor}
    init-sqls:
#    - "set time_zone='+0:00'"
    - "drop table if exists ClientDetails;"
    - "drop table if exists flyway_schema_history "
    - "drop table if exists oauth_access_token"
    - "drop table if exists oauth_approvals"
    - "drop table if exists oauth_client_details"
    - "drop table if exists oauth_client_token"
    - "drop table if exists oauth_code"
    - "drop table if exists oauth_refresh_token"
    - "drop table if exists users_roles"
    - "drop table if exists roles"
    - "drop table if exists users"
#    url: jdbc:mysql://localhost:3306/accountservice?useSSL=false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
