server:
  port: 6062
eureka:
  client:
    enabled: false

spring:
  datasource:
    username: sa
    password: newtouch
  h2:
    console:
      enabled: true
  messages:
    basename: messages, CommonExceptions
  flyway:
    locations: classpath:db/migration/{vendor}
