server:
  port: 6062
eureka:
  client:
    enabled: false

spring:
  datasource:
#    url: jdbc:h2:~/labrador-account;AUTO_SERVER=TRUE
    username: sa
    password: newtouch
  h2:
    console:
      enabled: true