server:
  port: 6060
eureka:
  client:
    enabled: false


whoami: from local
spring:
  datasource:
    url: jdbc:h2:~/labrador-account;AUTO_SERVER=TRUE
    username: sa
    password: newtouch
  h2:
    console:
      enabled: true