server:
  port: 6060

eureka:
  client:
    enabled: false

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1/accountservice?useSSL=false&allowPublicKeyRetrieval=true
  messages:
    basename: messages, CommonExceptions
  flyway:
    locations: classpath:db/migration/dev/{vendor}
    init-sqls:
    - "drop table if exists ClientDetails;"
    - "drop table if exists flyway_schema_history;"
    - "drop table if exists oauth_access_token;"
    - "drop table if exists oauth_approvals;"
    - "drop table if exists oauth_client_details;"
    - "drop table if exists oauth_client_token;"
    - "drop table if exists oauth_code;"
    - "drop table if exists oauth_refresh_token;"
    - "drop table if exists users_roles;"
    - "drop table if exists roles;"
    - "drop table if exists users;"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
