server:
  port: 6060
spring:
  datasource:
    username: sa
    password: newtouch
  h2:
    console:
      enabled: true
  messages:
    basename: messages, CommonExceptions
  flyway:
    locations: classpath:db/migration/dev/{vendor}
