server:
  port: 8763

zuul:
  sensitive-headers:
  routes:
    configservice:
      path: /config/**
    authservice:
      path: /auth/**
    sina:
      path: /sina/**
      url: http://news.sina.com.cn
desc: "zuul-local config-dev"
