spring:
  profiles:
    include:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/service-configrations/{application}, classpath:/service-configrations