spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:../service-configrations/{application}, file:../service-configrations
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/