spring:
  profiles:
    include:
      - native
  cloud:
    config:
      server:
        native:
          # 顺序决定了覆盖的顺序
          search-locations: classpath:/service-configurations/{profile}, classpath:/service-configurations/{profile}/{application}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

